server:
  port: 8082

spring:
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8080/eureka/
      defaultZone: http://172.17.0.2:8080/eureka/
      
  instance:
    instance-id: http://172.17.0.4:${server.port}
    prefer-ip-address: true
    ip-address: 172.17.0.4