server:
  port: 8086
spring:
  application:
    name: consumer-helloService-byFeign


eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8080/eureka/
      defaultZone: http://172.17.0.2:8080/eureka/
      
  instance:
    instance-id: http://172.17.0.8:${server.port}
    prefer-ip-address: true
    ip-address: 172.17.0.8
   
feign:
  hystrix:
    enabled: true