server:
  port: 8089
spring:
  application:
    name: springcloud-zuul-client


eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8080/eureka/
      defaultZone: http://172.17.0.2:8080/eureka/
      
  instance:
    instance-id: http://172.17.0.11:${server.port}
    prefer-ip-address: true
    ip-address: 172.17.0.11 
   
feign:
  hystrix:
    enabled: true
    
management:
    endpoints:
       web:
          exposure:
             include: "*"    